# Generated by Django 4.1.5 on 2023-01-11 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='car name')),
                ('Variant', models.CharField(max_length=50)),
                ('Model_Date', models.DateField()),
                ('Price', models.IntegerField(verbose_name='car price')),
                ('Description', models.TextField(verbose_name='car description')),
                ('Mileage', models.IntegerField()),
                ('Power', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('to_sell', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Icon', models.ImageField(upload_to='model_icons')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('IsAnswered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FrequesntAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField()),
                ('QuestionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkinternational.frequentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='car_picture', verbose_name='Car Image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkinternational.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkinternational.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkinternational.carmodel'),
        ),
    ]
